### ISSUE TITLE
Exception launching pio train

### ISSUE THREAD

**Issue by salgua** [PredictionIO/template-scala-parallel-similarproduct#2]
pio train doesn't work. It throws the following exception:

    Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: viewEvents in       PreparedData cannot be empty. Please check if DataSource generates TrainingData and Preprator  generates PreparedData correctly.

with other templates it works fine

**Comment by k4hoo** [comment]
By the default, the template requires view event imported. Seems you don't have view events for you app. Does the appId specified in engine.json match the app you want to use? Did you run the python script to import sample data?
To debug:
1) check what's the appId specified in engine.json
2) run "pio app list"
3) find the app for that app ID, you can see the app name, access_key
4) run eventserver by "pio eventserver"
5) with the access key, you can query eventserver with browser and see if any view event
http://localhost:7070/events.json?accessKey=<your_access_key>&event=view
6) if empty, means you there is no "view" events for the corresponding app

**Comment by salgua** [comment]
It was my mistake! I didn't import any sample data. Now I imported them and it works fine. Thank you!
