### ISSUE TITLE
Multiple item (entity) types

### ISSUE THREAD

**Issue by stocarul** [PredictionIO/template-scala-parallel-similarproduct#6]
Is it possible to have multiple item (entity) types, for example `article` and `event`, and for an article to get similar articles and for an event to get similar events?

**Comment by k4hoo** [comment]
yes. you can use different entityTypes and modify engine data source to read the corresponding entityTypes for training (https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/v0.3.2/src/main/scala/DataSource.scala#L68)
Or you can set those as "categories" of item and specify categories you want in the query.

**Comment by stocarul** [comment]
Thank you for the answer!
