### ISSUE TITLE
Blacklist category

### ISSUE THREAD

**Issue by cuongthamhl** [PredictionIO/template-scala-parallel-similarproduct#7]
Is currently a way to blacklist certain categories?

**Comment by k4hoo** [comment]
no. but seems a good feature in addition to current whitelist-categories.
can easily change for this.
add one more field in query
https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/v0.3.2/src/main/scala/Engine.scala#L9

and modify isCandidate function here
https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/v0.3.2/src/main/scala/ALSAlgorithm.scala#L220

pull request is welcome :)
